[tool.pytest.ini_options]
env_override_existing_values = 1
env_files = [".env"]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "login: All login tests",
    "login_success: Login tests with a user who is not locked out.",
]